In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt



#loading dataset 

data =pd.read_csv('tesla_q1_2024.csv')

print("data Columns:")
print(data.columns.tolist())

data Columns:
['($ in millions, except percentages and per share data)', 'Q1-2023', 'Q2-2023', 'Q3-2023', 'Q4-2023', 'Q1-2024', 'YoY', 'Unnamed: 7', 'Current Installed Annual Vehicle Capacity', 'Unnamed: 9', 'None_1', 'None_2', 'None_3', 'None_4', 'None_5', 'None_6', 'None_7', 'None_8', 'None_9', 'None_10', 'None_11', 'None_12', 'None_13', '_1', '_2', '_3', '_4', 'None_14', 'None_15', 'None_16', 'None_17', 'None_18', 'None_19', 'None_20', 'None_21', 'None_22', 'None_23', 'None_24', 'None_25', 'None_26', 'None_27', 'None_28', 'None_29', 'None_30', 'None_31', 'None_32', 'None_33', 'REVENUES', 'ASSETS', 'CASH FLOWS FROM OPERATING ACTIVITIES', '_5', 'In millions of USD', '3Q-2020', '4Q-2020', '1Q-2021', '2Q-2021', '3Q-2021', '4Q-2021', '1Q-2022', '2Q-2022', '3Q-2022', '4Q-2022', '1Q-2023', '2Q-2023', '3Q-2023', '4Q-2023', '1Q-2024']

In [3]:
# Iterate through each column in the dataset
for column_name, series in data.items():
    # Calculate missing values for each column
    missing_values = series.isnull().sum()
    
    # Check if the column has any missing values
    if missing_values > 0:
        print(f"\nMissing values in '{column_name}': {missing_values}")

Missing values in '($ in millions, except percentages and per share data)': 313

Missing values in 'Q1-2023': 299

Missing values in 'Q2-2023': 299

Missing values in 'Q3-2023': 299

Missing values in 'Q4-2023': 299

Missing values in 'Q1-2024': 299

Missing values in 'YoY': 299

Missing values in 'Unnamed: 7': 314

Missing values in 'Current Installed Annual Vehicle Capacity': 324

Missing values in 'Unnamed: 9': 322

Missing values in 'None_1': 322

Missing values in 'None_2': 322

Missing values in 'None_3': 332

Missing values in 'None_4': 332

Missing values in 'None_5': 332

Missing values in 'None_6': 332

Missing values in 'None_7': 332

Missing values in 'None_8': 332

Missing values in 'None_9': 332

Missing values in 'None_10': 332

Missing values in 'None_11': 332

Missing values in 'None_12': 332

Missing values in 'None_13': 332

Missing values in '_1': 328

Missing values in '_2': 328

Missing values in '_3': 328

Missing values in '_4': 247

Missing values in 'None_14': 332

Missing values in 'None_15': 332

Missing values in 'None_16': 332

Missing values in 'None_17': 332

Missing values in 'None_18': 332

Missing values in 'None_19': 332

Missing values in 'None_20': 332

Missing values in 'None_21': 332

Missing values in 'None_22': 332

Missing values in 'None_23': 332

Missing values in 'None_24': 332

Missing values in 'None_25': 332

Missing values in 'None_26': 332

Missing values in 'None_27': 332

Missing values in 'None_28': 332

Missing values in 'None_29': 332

Missing values in 'None_30': 332

Missing values in 'None_31': 332

Missing values in 'None_32': 332

Missing values in 'None_33': 332

Missing values in 'REVENUES': 326

Missing values in 'ASSETS': 331

Missing values in 'CASH FLOWS FROM OPERATING ACTIVITIES': 330

Missing values in '_5': 313

Missing values in 'In millions of USD': 312

Missing values in '3Q-2020': 322

Missing values in '4Q-2020': 322

Missing values in '1Q-2021': 322

Missing values in '2Q-2021': 312

Missing values in '3Q-2021': 312

Missing values in '4Q-2021': 312

Missing values in '1Q-2022': 312

Missing values in '2Q-2022': 312

Missing values in '3Q-2022': 312

Missing values in '4Q-2022': 312

Missing values in '1Q-2023': 312

Missing values in '2Q-2023': 312

Missing values in '3Q-2023': 312

Missing values in '4Q-2023': 312

Missing values in '1Q-2024': 312

In [4]:

#drop the null values 
data=data.dropna()

In [6]:
# Drop rows with any null values
data_cleaned = data.dropna()

# Check the cleaned dataset for any remaining missing values
missing_values_after_drop = data_cleaned.isnull().sum()
non_zero_missing_values_after_drop = missing_values_after_drop[missing_values_after_drop > 0]

# Print if there are still any missing values
if not non_zero_missing_values_after_drop.empty:
    print("There are still missing values in the dataset:")
    print(non_zero_missing_values_after_drop)
else:
    print("No missing values remain in the dataset after dropping rows.")
    
# Optionally, you can display the first few rows of the cleaned data
print(data_cleaned.head())

No missing values remain in the dataset after dropping rows.
Empty DataFrame
Columns: [($ in millions, except percentages and per share data), Q1-2023, Q2-2023, Q3-2023, Q4-2023, Q1-2024, YoY, Unnamed: 7, Current Installed Annual Vehicle Capacity, Unnamed: 9, None_1, None_2, None_3, None_4, None_5, None_6, None_7, None_8, None_9, None_10, None_11, None_12, None_13, _1, _2, _3, _4, None_14, None_15, None_16, None_17, None_18, None_19, None_20, None_21, None_22, None_23, None_24, None_25, None_26, None_27, None_28, None_29, None_30, None_31, None_32, None_33, REVENUES, ASSETS, CASH FLOWS FROM OPERATING ACTIVITIES, _5, In millions of USD, 3Q-2020, 4Q-2020, 1Q-2021, 2Q-2021, 3Q-2021, 4Q-2021, 1Q-2022, 2Q-2022, 3Q-2022, 4Q-2022, 1Q-2023, 2Q-2023, 3Q-2023, 4Q-2023, 1Q-2024]
Index: []

[0 rows x 67 columns]

In [8]:
#save csv file 
data.to_csv("cleanned_tesla_q1_2024.csv", index=False)